### ISSUE TITLE
DSD: Infomodel contradiction between minOccurs and usageType

### ISSUE THREAD

**Issue by buhaiovos** [sdmx-twg/sdmx-im#26]
Hello!

Working with the Infomodel, we have stumbled upon one particular thing:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/22531086/232825258-ee8538a0-8aaa-401d-8a94-7511a35b7deb.png">

IM describes (section 5.3) data attributes and measures of DSD having both `minOccurs/maxOccurs` and `usage` attributes. And it's the `usage` attribute which dictates whether the measure (or data attribute) is mandatory. But the question which arises, is how implementors should handle situations when there is a structure which declares, say, `minOccurs=0` and `usage=mandatory`? They seem to contradict to each other. 

At the same time, in the description of metadata structure definition - metadata attributes specifically, there is no `usage` property and the requirement of the attribute is derived from the `minOccurs` value, i.e `0` standing for optional and `>=1` standing for mandatory. Should DSD be similar to this?

Thanks!

**Comment by stratosn** [comment]
Dear @buhaiovos thanks for the questions and apologies for the long turnaround.

As regards the first issue, the point of having both usage and minOccurs is required for the use-cases were a Measure or Attribute has to be reported by a minimum set of occurrences regardless of the need or not to report it. While the `minOccurs=0` + `usage=mandatory` may seem a bit strange (but has to be handled at a business rule level), the `minOccurs=3` + `usage=Optional` would not be possible otherwise.

As regards the reference metadata, the case is a bit different compared to the data, since MetadataAttributes can also contain other MetadataAttributes (which is not the case for data Attributes and Measures), thus it would not be possible to implement it the same way as for data. This means that the same can be implemented a bit differently in metadatasets (which was already there before even introducing multiple values for Attributes/Measures in datasets).

**Comment by tmartine** [comment]
Hi! I know I should panic but I tried finding you on confluence. Do you
need me to add you on my reminder ? I seriously have no way of knowing if
you want to be credited for your invisible presence or not.. I it makes me
panic. Could you please tell me what you think ? Best

Martine Tchitchihe
612 402 1978
*''L’école est une clef pour la vie" Baba Simon*
*"Teachers plant seeds of knowledge that last a lifetime"*

**Comment by stratosn** [comment]
Considered as solved, following the acceptance by the author.
